export enum NotificationType {
	MY_COMMENT_REPLY = 'MY_COMMENT_REPLY',
	MY_COMMENT_LIKE = 'MY_COMMENT_LIKE',
	MY_COMMENT_LIKE_CANCLE = 'MY_COMMENT_LIKE_CANCLE',
	MY_COMMENT_REPLY_MENTION = 'MY_COMMENT_REPLY_MENTION',
	MY_POST_REPLY = 'MY_POST_REPLY',
	MY_POST_LIKE = 'MY_POST_LIKE',
	MY_POST_LIKE_CANCLE = 'MY_POST_LIKE_CANCLE',
}
